// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClE7RhoOCV51xUfjlXcwj6OsEVAMdVhAc',
    appId: '1:593037562166:web:6995176762e1772b306397',
    messagingSenderId: '593037562166',
    projectId: 'prmda-27af3',
    authDomain: 'prmda-27af3.firebaseapp.com',
    storageBucket: 'prmda-27af3.appspot.com',
    measurementId: 'G-72XS75K1H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD3jmLhS5IBCjCXN7Uw2tIw_nnyHX5ZAU',
    appId: '1:593037562166:android:37536778ce675885306397',
    messagingSenderId: '593037562166',
    projectId: 'prmda-27af3',
    storageBucket: 'prmda-27af3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlIgsdpNKZCH3xTA6_ZEcfLkEeHSXbB2M',
    appId: '1:593037562166:ios:c35cd499543d4383306397',
    messagingSenderId: '593037562166',
    projectId: 'prmda-27af3',
    storageBucket: 'prmda-27af3.appspot.com',
    iosBundleId: 'com.example.prmda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlIgsdpNKZCH3xTA6_ZEcfLkEeHSXbB2M',
    appId: '1:593037562166:ios:c35cd499543d4383306397',
    messagingSenderId: '593037562166',
    projectId: 'prmda-27af3',
    storageBucket: 'prmda-27af3.appspot.com',
    iosBundleId: 'com.example.prmda',
  );
}
